### ISSUE TITLE
must be install ext: fileinfo?

### ISSUE THREAD

**Issue by qiuyuhome** [gumlet/php-image-resize#101]
```
PHP Fatal error:  Call to undefined function Gumlet\finfo_open()
```

```
[spider@ns543625 coupons_deals]$    php -m | grep fileinfo
[spider@ns543625 coupons_deals]$
```

**Comment by kenw2004** [comment]
yes

**Comment by qiuyuhome** [comment]
# @kenw2004 
![image](https://user-images.githubusercontent.com/17526777/35471940-915a0e0a-03a0-11e8-8847-e31441fead39.png)

There is no hint.

**Comment by adityapatadia** [comment]
Where do you get the error? Can you give us part of your code from where this error is thrown? I would look into it as soon as you provide more info.

**Comment by adityapatadia** [comment]
I would also suggest you give us your PHP version and any other required info as well.

**Comment by adityapatadia** [comment]
Let me also know what version of library do you use. Are you using master branch? I checked with PHP 7.1 and 1.7 version of this library and everything seems to be working fine.

**Comment by peter279k** [comment]
This will be solved when merging this [PR](https://github.com/gumlet/php-image-resize/pull/103/).
And Composer will output error message if the PHP doesn't have the ```fileinfo``` extension.

**Comment by adityapatadia** [comment]
It's resolved in ```1.8.0```

**Comment by IamAlta** [comment]
Just downloaded your program today and got this error.

**Comment by peter279k** [comment]
@IamAlta, please use the ```composer``` to download this package.
And it will check the whether ```fieinfo``` is installed.
Also, you have to install the ```fileinfo``` extension by yourself.

Thanks.

**Comment by IamAlta** [comment]
Thanks. fileinfo was installed by our techs. It still doesn't work so I coded my own.
